-- ROUND FUNCTION
select round(22.8);

-- FLOOR  FUNCTION
SELECT floor(3.3);

-- CEILING FUNCTION
SELECT ceiling(3.3);

-- TRUNCATR FUNCTION
SELECT truncate(3.6663,1);

-- ABS FUNCTION 
SELECT abs(-99);